[project]
name = "MariaDB_Context_Manager"
version = "2.0.0"
authors = [
  { name="Antony", email="antonygradillas@gmail.com" },
]
description = "An easy to use mariadb context manager"
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["mariadb", "automation", "sql"]
requires-python = ">=3.11"
dependencies = [
  "mariadb>=1.1.14",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/avgra3/MariaDB-Context-Manager"
Repository = "https://github.com/avgra3/MariaDB-Context-Manager"
Issues = "https://github.com/avgra3/MariaDB-Context-Manager/issues"


[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
extend-select = ["E501"]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
