name: Publish mariadb-context-manager to PyPi and TestPyPi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
      name: Build distribution
      #runs-on: self-hosted
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python_version: ["3.12"]
      steps:
      - uses: actions/checkout@v4
      - name: Setting up python
        uses: actions/setup-python@v5
        with:
          #python-version: "${{ matrix.python_version }}"
          python-version: "3.x"
          allow-prereleases: false
      - name: Install mariadb-connector-c
        run: sudo apt-get install -y mariadb-client
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    needs: [build]
    name: >-
        Publish Python package to PyPI
    if: startsWith(github.ref, 'refs/tags/v') # Only publish to PyPI on tag pushes
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      name: pypi
      url: https://pypi.org/p/MariaDB-Context-Manager
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distribution
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to Github Release
    needs:
    - publish-to-pypi
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""
      - name: Upload artifact signatures to GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Upload to GitHub Release using the `gh` CLI.
          # `dist/` contains the built packages, and the
          # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'
